[workspace]
members = [
  "crates/embedded-idp-core",
  "crates/embedded-idp-security",
  "crates/embedded-idp-email",
  "crates/embedded-idp-axum",
  "crates/embedded-idp-storage-postgres",
  "crates/embedded-idp-app",
  "examples/no-tenant-host"
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "3.0.0"
license = "MIT"
publish = false
repository = "https://github.com/ooctoo/rust-embedded-idp"
